# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-10 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appserver', '0002_auto_20190110_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammer_language', models.IntegerField(default=2)),
                ('no_of_words', models.IntegerField(default=2)),
                ('journal_title', models.IntegerField(default=2)),
                ('author_nationality', models.IntegerField(default=2)),
                ('article_type', models.IntegerField(default=2)),
                ('score', models.CharField(default='Intermidiate', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document',
        ),
        migrations.RemoveField(
            model_name='document',
            name='score',
        ),
        migrations.AddField(
            model_name='document',
            name='abstract',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='document',
            name='expect_topic',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='document',
            name='obtain_topic',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='overallscore',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_document', to='appserver.Document'),
        ),
    ]
