# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-11 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appserver', '0003_auto_20190110_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
