# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-11 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appserver', '0004_document_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
