# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-14 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appserver', '0005_auto_20190111_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
