# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-11 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('appserver', '0006_document_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallscore',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scoregroup', to='auth.Group'),
            preserve_default=False,
        ),
    ]
