version: '3.7'
services:
    main_engine:
        image: "spianalytics/lang_asses_acs:1.0b3"
        container_name: "la_acs_engine"
        ports:
            - "8003:8000"
        volumes:
            - ../la_acs_log_dir:/home/la_acs_user/la_acs_deployment/la_acs_log_dir
            - ./server:/home/la_acs_user/la_acs_deployment/server
            - ./language_assessment_core:/home/la_acs_user/la_acs_deployment/language_assessment_core

        command: /bin/bash /home/la_acs_user/la_acs_deployment/server/run_devel_server.sh
        # networks:
        #     la_acs_network:
        #         ipv4_address: 172.26.1.2
        depends_on:
            - mysql_database

    mysql_database:
        image: 'mysql/mysql-server:5.7'
        ports:
          - "3316:3306"
        container_name: 'la_acs_mysql_container'
        environment:
          - MYSQL_ROOT_PASSWORD=root
          # - MYSQL_DATABASE=LA_ACS_dev
            # - MYSQL_USER=dbadmin
            # - MYSQL_PASSWORD=dbadmin123
        volumes:
          - ../la_acs_datavolume:/var/lib/mysql
        # networks:
        #    la_acs_network:
        #       ipv4_address: 172.26.1.3

# networks:
#     la_acs_network:
#         ipam:
#             driver: default
#             config:
#                 - subnet: 172.26.0.0/16
